-- Imperium Task Manager — v2: multi-tenant SaaS schema with auth.
-- Run this in the Supabase SQL editor. It REPLACES the v1 demo schema
-- (drops the old tables and their data).
--
-- Model: every row belongs to a company. Users sign up either with a
-- company_name (creating a new company, becoming its manager) or with an
-- invite code generated by a manager (joining that company as crew/manager).

-- ── drop v1 ─────────────────────────────────────────────────────────
drop table if exists public.time_entries cascade;
drop table if exists public.messages cascade;
drop table if exists public.issues cascade;
drop table if exists public.checklist_items cascade;
drop table if exists public.jobs cascade;

-- ── tables ──────────────────────────────────────────────────────────
create table public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  company_id uuid not null references public.companies (id) on delete cascade,
  full_name text not null,
  role text not null default 'crew' check (role in ('manager', 'crew')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.invites (
  code text primary key,
  company_id uuid not null references public.companies (id) on delete cascade,
  role text not null default 'crew' check (role in ('manager', 'crew')),
  created_by uuid not null references public.profiles (id) on delete cascade,
  used_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  used_at timestamptz
);

create table public.jobs (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id) on delete cascade,
  client text not null,
  address text not null,
  time_label text not null default '',
  assignee_id uuid references public.profiles (id) on delete set null,
  status text not null default 'todo'
    check (status in ('todo', 'inprogress', 'submitted', 'approved')),
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.checklist_items (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.jobs (id) on delete cascade,
  company_id uuid not null references public.companies (id) on delete cascade,
  label text not null,
  done boolean not null default false,
  photo_path text,          -- storage path in the job-photos bucket
  position integer not null default 0
);

create table public.issues (
  id bigint generated always as identity primary key,
  company_id uuid not null references public.companies (id) on delete cascade,
  author_id uuid not null references public.profiles (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

-- One thread per crew member (thread_id = that member's profile id);
-- managers can read and write every thread.
create table public.messages (
  id bigint generated always as identity primary key,
  company_id uuid not null references public.companies (id) on delete cascade,
  thread_id uuid not null references public.profiles (id) on delete cascade,
  sender_id uuid not null references public.profiles (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create table public.time_entries (
  id bigint generated always as identity primary key,
  company_id uuid not null references public.companies (id) on delete cascade,
  employee_id uuid not null references public.profiles (id) on delete cascade,
  clock_in timestamptz not null default now(),
  clock_out timestamptz
);

create index profiles_company_idx on public.profiles (company_id);
create index jobs_company_idx on public.jobs (company_id);
create index checklist_items_job_idx on public.checklist_items (job_id);
create index checklist_items_company_idx on public.checklist_items (company_id);
create index issues_company_idx on public.issues (company_id);
create index messages_company_idx on public.messages (company_id);
create index messages_thread_idx on public.messages (thread_id);
create index time_entries_company_idx on public.time_entries (company_id);
create index time_entries_open_idx on public.time_entries (employee_id) where clock_out is null;

-- ── helper functions (security definer: avoid RLS recursion) ────────
create or replace function public.current_company_id()
returns uuid language sql stable security definer set search_path = public as
$$ select company_id from profiles where id = auth.uid() $$;

create or replace function public.is_manager()
returns boolean language sql stable security definer set search_path = public as
$$ select exists (select 1 from profiles where id = auth.uid() and role = 'manager') $$;

-- Pre-signup check so apps can validate a code before creating the user.
create or replace function public.validate_invite(p_code text)
returns boolean language sql stable security definer set search_path = public as
$$ select exists (select 1 from invites where code = upper(p_code) and used_by is null) $$;

grant execute on function public.validate_invite(text) to anon, authenticated;

-- ── signup trigger ───────────────────────────────────────────────────
-- raw_user_meta_data drives onboarding:
--   { company_name, full_name }  → new company, role manager
--   { invite_code, full_name }   → join invite's company with invite's role
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as
$$
declare
  meta jsonb := new.raw_user_meta_data;
  v_company uuid;
  v_role text;
  v_invite invites%rowtype;
  v_name text := coalesce(nullif(trim(meta ->> 'full_name'), ''), split_part(new.email, '@', 1));
begin
  if nullif(trim(meta ->> 'company_name'), '') is not null then
    insert into companies (name) values (trim(meta ->> 'company_name')) returning id into v_company;
    v_role := 'manager';
  elsif nullif(trim(meta ->> 'invite_code'), '') is not null then
    select * into v_invite from invites
      where code = upper(trim(meta ->> 'invite_code')) and used_by is null
      for update;
    if not found then
      raise exception 'Invalid or already-used invite code';
    end if;
    v_company := v_invite.company_id;
    v_role := v_invite.role;
  else
    raise exception 'Signup requires a company_name or an invite_code';
  end if;

  insert into profiles (id, company_id, full_name, role)
  values (new.id, v_company, v_name, v_role);

  if v_invite.code is not null then
    update invites set used_by = new.id, used_at = now() where code = v_invite.code;
  end if;

  return new;
end
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── row level security ───────────────────────────────────────────────
alter table public.companies enable row level security;
alter table public.profiles enable row level security;
alter table public.invites enable row level security;
alter table public.jobs enable row level security;
alter table public.checklist_items enable row level security;
alter table public.issues enable row level security;
alter table public.messages enable row level security;
alter table public.time_entries enable row level security;

create policy "members read own company" on public.companies
  for select using (id = public.current_company_id());
create policy "managers update own company" on public.companies
  for update using (id = public.current_company_id() and public.is_manager());

create policy "members read company profiles" on public.profiles
  for select using (company_id = public.current_company_id());
create policy "users update own profile" on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid());
create policy "managers update company profiles" on public.profiles
  for update using (company_id = public.current_company_id() and public.is_manager());

create policy "managers manage invites" on public.invites
  for all using (company_id = public.current_company_id() and public.is_manager())
  with check (company_id = public.current_company_id() and public.is_manager());

create policy "members read company jobs" on public.jobs
  for select using (company_id = public.current_company_id());
create policy "managers insert jobs" on public.jobs
  for insert with check (company_id = public.current_company_id() and public.is_manager());
create policy "managers or assignee update jobs" on public.jobs
  for update using (company_id = public.current_company_id()
    and (public.is_manager() or assignee_id = auth.uid()))
  with check (company_id = public.current_company_id()
    and (public.is_manager() or (assignee_id = auth.uid() and status <> 'approved')));
create policy "managers delete jobs" on public.jobs
  for delete using (company_id = public.current_company_id() and public.is_manager());

create policy "members read company items" on public.checklist_items
  for select using (company_id = public.current_company_id());
create policy "managers insert items" on public.checklist_items
  for insert with check (company_id = public.current_company_id() and public.is_manager());
create policy "managers or assignee update items" on public.checklist_items
  for update using (company_id = public.current_company_id()
    and (public.is_manager()
      or exists (select 1 from public.jobs j where j.id = job_id and j.assignee_id = auth.uid())))
  with check (company_id = public.current_company_id());
create policy "managers delete items" on public.checklist_items
  for delete using (company_id = public.current_company_id() and public.is_manager());

create policy "members read company issues" on public.issues
  for select using (company_id = public.current_company_id());
create policy "members report issues" on public.issues
  for insert with check (company_id = public.current_company_id() and author_id = auth.uid());

create policy "own thread or manager reads messages" on public.messages
  for select using (company_id = public.current_company_id()
    and (public.is_manager() or thread_id = auth.uid()));
create policy "own thread or manager sends messages" on public.messages
  for insert with check (company_id = public.current_company_id()
    and sender_id = auth.uid()
    and (public.is_manager() or thread_id = auth.uid()));

create policy "members read company time entries" on public.time_entries
  for select using (company_id = public.current_company_id());
create policy "employees insert own time entries" on public.time_entries
  for insert with check (company_id = public.current_company_id() and employee_id = auth.uid());
create policy "employee or manager updates time entries" on public.time_entries
  for update using (company_id = public.current_company_id()
    and (employee_id = auth.uid() or public.is_manager()))
  with check (company_id = public.current_company_id());

-- ── storage: job photos ──────────────────────────────────────────────
-- Private bucket; paths are <company_id>/<job_id>/<item_id>-<ts>.jpg and
-- access is scoped to the caller's company via the first path segment.
insert into storage.buckets (id, name, public)
values ('job-photos', 'job-photos', false)
on conflict (id) do nothing;

create policy "company reads own job photos" on storage.objects
  for select using (
    bucket_id = 'job-photos'
    and (storage.foldername(name))[1] = public.current_company_id()::text
  );
create policy "company uploads own job photos" on storage.objects
  for insert with check (
    bucket_id = 'job-photos'
    and (storage.foldername(name))[1] = public.current_company_id()::text
  );
create policy "company replaces own job photos" on storage.objects
  for update using (
    bucket_id = 'job-photos'
    and (storage.foldername(name))[1] = public.current_company_id()::text
  );

-- ── realtime ─────────────────────────────────────────────────────────
alter publication supabase_realtime add table
  public.jobs, public.checklist_items, public.issues,
  public.messages, public.time_entries, public.profiles, public.invites;
